### PR TITLE
Add GNOME 47 Support

### PR DESCRIPTION
**Pull request by 8Dion8**
Just added the version number and it works.

### CODE REVIEW

**Comment by mzur** [comment]
@8Dion8: Thanks!

@Cub11k: The more people confirm that it just works here, the more likely I am to merge the PR without testing it myself (which might take quite a while for me to find the time for).

**Comment by sovanyio** [comment]
Just modified my local copy and it is working after logging out/in.

**Comment by balazsvajdics** [comment]
It works correctly for me as well!

**Comment by mzur** [comment]
Ok thanks everyone!

**Review by mzur — APPROVED** [review]

**Pull request merged**
