### PR TITLE
Gnome 43 support

### PR DESCRIPTION
**Pull request by Eeems**
I didn't bother with backwards compatibility.

### CODE REVIEW

**Comment by Eeems** [comment]
I've also exposed the indicator that this overwrites so that it's easier to poke around at what is happening in looking-glass.

**Comment by Eeems** [comment]
@mzur poke? Is there anything you'd like me to change before this can be merged?

**Comment by mzur** [comment]
Sorry I've just got too much on my plate right now. I didn't get around to upgrade my testing VM to GNOME 43 and my laptop currently has no battery, of all things. But I applied your changes with GNOME 43 now and saw no errors. So I'll trust that everything will work :wink:

Thanks for sending the PR!

**Comment by Eeems** [comment]
I've been running it since it opened with no issue so far, so hopefully there isn't an issue that both of us missed 😅

**Pull request merged**
